AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs simple sentence.
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      Runtime: python3.8
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /test-pipeline-acg
            Method: GET